server:
  port: 10000

logging:
  level:
    com.atguigu.gulimall.product: INFO

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 360000
      key-prefix: CACHE_
      cache-null-values: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


gulimall:
  thread:
    core-pool-size: 20
    max-pool-size: 100
    keep-alive-time: 60
